services:
  afl:
    container_name: afl-integration
    image: aflplusplus/aflplusplus
    command: sleep infinity
    volumes:
      - ./llm_mutator.py:/afl/llm_mutator.py
      - ./workspace:/workspace
    